# Generated by Django 5.2 on 2025-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_buildingtype_options_alter_saletype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(upload_to='property_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='property_images'),
        ),
    ]
